---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunnybikes
  namespace: sunnybikes
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  selector:
    matchLabels:
      app: sunnybikes
  template:
    metadata:
      labels:
        app: sunnybikes
    spec:
      containers:
        - name: sunnybikes
          image: pradaelli/sunnybikes
          imagePullPolicy: IfNotPresent
          env:
            - name: PG_PASSWORD
              value: "long-distance-ice-skating"
              # valueFrom:
              #   secretKeyRef:
              #     name: postgres-secret
              #     key: POSTGRES_PASSWORD
            - name: PG_HOST
              value: postgres.sunnybikes.svc.cluster.local
            - name: PG_PORT
              value: "5432"
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              port: 5000
              path: /hello
---
apiVersion: v1
kind: Service
metadata:
  name: sunnybikes
  namespace: sunnybikes
spec:
  type: NodePort
  selector:
    app: sunnybikes
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30800
      protocol: TCP
