apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.grafana.name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.grafana.name }}
  type: NodePort
  ports:
    - port: {{ .Values.grafana.ports.frontend }}
      targetPort: grafana
