apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.otelCollector.name }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.otelCollector.ports.grpc }}
      targetPort: {{ .Values.otelCollector.ports.grpc }}
      nodePort: 30080 # the port to map to on the node
  selector:
    app: {{ .Release.Name }}-{{ .Values.otelCollector.name }}
