apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.grafanaTempo.name }}-config
data:
  tempo.yaml: |
    server:
      http_listen_port: {{ .Values.grafanaTempo.ports.backend }}

    distributor:
      receivers:
        otlp:
          protocols:
            http:
            grpc:

    storage:
      trace:
        backend: local
        wal:
          path: /tmp/tempo/wal
        local:
          path: /tmp/tempo/blocks
