apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hide-secrets
  namespace: sunnybikes
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hide-secrets
  namespace: sunnybikes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hide-secrets
subjects:
  - kind: User
    name: timvancann@godatadriven.com
