# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-postgres
#   labels:
#     type: local
# spec:
#   storageClassName: hostpath
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sunnybikes
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "long-distance-ice-skating"
              # valueFrom:
              #   secretRef:
              #     name: postgres-secret
              #     key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: init
            - mountPath: /var/lib/postgresql/data
              name: data
              subPath: data
          ports:
            - containerPort: 5432
      volumes:
        - name: init
          configMap:
            name: postgres-init
        - name: data
          persistentVolumeClaim:
            claimName: pvc-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sunnybikes
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
